<a href="https://colab.research.google.com/github/aoaguirre123/Proyecto3_Examen/blob/main/Clase_26_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/content/online_casino_games_dataset_v2.csv')

/tmp/ipykernel_2158/1213801290.py:1: DtypeWarning: Columns (14,15,16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/online_casino_games_dataset_v2.csv')

In [3]:
df.head()

,casino,game,provider,rtp,volatility,jackpot,country_availability,min_bet,max_win,game_type,game_category,license_jurisdiction,release_year,currency,mobile_compatible,free_spins_feature,bonus_buy_available,max_multiplier,languages,last_updated
0,Guts Casino,Texas Hold'em Bonus,Saucify,98.83,Medium,NaN,AR|BR|CH|CO|CY|DE|EE|ES|IE|IL|KE|MT|NZ|PE|PT|R...,1.00,435957.16,poker,Video Poker,MGA,2021.0,SEK|USD,True,False,False,356.0,EN|ES|TR|IT|JA|DE|FR|CS,2024-09-20
1,Expekt,Mines,Playtech,98.05,Low,NaN,BG|HR|ID|LT|NO|PH|SE|TR,0.25,1396.15,crash,Crash,Curaçao,2018.0,NZD|BRL|CAD|SEK|AUD,True,False,False,206.0,EN|SV|TR|ZH|PT|ES|FR|JA,2024-02-03
2,Betinia,Mega Vault,Gamomat,95.43,Very High,NaN,CH|ES|GB|HU|ID|IE|IN|LT|NO|SE|SG|VN,0.10,1180.12,slot,3D Slot,Isle of Man,2014.0,NZD|AUD|BRL|GBP|CAD,True,True,False,1787.0,EN|DE|FI|HU|PT|ZH|FR|JA,2024-07-09
3,Pinnacle,Casino Hold'em Pro,4ThePlayer,99.50,Medium,NaN,BE|BR|MY|NG|PL,0.05,236507.50,poker,Three Card Poker,MGA,2023.0,DKK|NZD|SEK,True,False,False,369.0,EN|ES|SV|DA|CS|FR|ZH|FI|NO|PT|HU|KO,2024-06-27
4,Winnerz,Solar Star Xtreme,Hacksaw Gaming,97.18,High,NaN,CL|KE|PT|SG|SI,0.20,1093.45,slot,Jackpot Slot,MGA,2022.0,NOK|GBP,True,True,False,1970.0,EN|JA|PT|KO|ES,2024-04-24

In [14]:
df.columns

Index(['casino', 'game', 'provider', 'rtp', 'volatility', 'jackpot',
       'country_availability', 'min_bet', 'max_win', 'game_type',
       'game_category', 'license_jurisdiction', 'release_year', 'currency',
       'mobile_compatible', 'free_spins_feature', 'bonus_buy_available',
       'max_multiplier', 'languages', 'last_updated'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 134619 entries, 0 to 134618
Data columns (total 20 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   casino                134619 non-null  object
 1   game                  134619 non-null  object
 2   provider              134619 non-null  object
 3   rtp                   134619 non-null  float64
 4   volatility            134619 non-null  object
 5   jackpot               14497 non-null   object
 6   country_availability  134619 non-null  object
 7   min_bet               134619 non-null  float64
 8   max_win               134619 non-null  float64
 9   game_type             134618 non-null  object
 10  game_category         134618 non-null  object
 11  license_jurisdiction  134618 non-null  object
 12  release_year          134618 non-null  float64
 13  currency              134618 non-null  object
 14  mobile_compatible     134618 non-null  object
 15  free_spins_feature    134618 non-null  object
 16  bonus_buy_available   134618 non-null  object
 17  max_multiplier        110476 non-null  float64
 18  languages             134618 non-null  object
 19  last_updated          134618 non-null  object
dtypes: float64(5), object(15)
memory usage: 20.5+ MB

In [15]:
df['game_category'].value_counts()

game_category
Branded Slot        6960
Video Slot          6917
Jackpot Slot        6895
Cluster Pays        6888
Megaways            6846
3D Slot             6807
Classic Slot        6766
Casino Hold'em      3943
Caribbean Poker     3906
Live Poker          3874
Live Roulette       3853
Video Poker         3848
Three Card Poker    3831
Other Poker         3824
Live Baccarat       3779
Live Game Show      3771
Live Blackjack      3742
Instant Lottery     3299
Craps               3254
Baccarat            3206
Poker Table         3199
Blackjack           3195
Scratch Card        3185
Instant Win         3176
Other Table         3173
Roulette            3135
Crash               2026
80-Ball Bingo       1972
75-Ball Bingo       1956
Other Crash         1942
Slingo              1934
Speed Bingo         1919
Mines               1917
Plinko              1903
90-Ball Bingo       1893
HiLo                1884
Name: count, dtype: int64

In [8]:
df['free_spins_feature'].value_counts()

free_spins_feature
False    98579
True     36039
Name: count, dtype: int64

In [9]:
df.isnull().sum() # Identificar los valores nulos

casino                       0
game                         0
provider                     0
rtp                          0
volatility                   0
jackpot                 120122
country_availability         0
min_bet                      0
max_win                      0
game_type                    1
game_category                1
license_jurisdiction         1
release_year                 1
currency                     1
mobile_compatible            1
free_spins_feature           1
bonus_buy_available          1
max_multiplier           24143
languages                    1
last_updated                 1
dtype: int64

In [10]:
df.describe().round() # Toma las columas numericas y obtiene estadistica descriptiva de las mismas.

            rtp   min_bet    max_win  release_year  max_multiplier
count  134619.0  134619.0   134619.0      134618.0        110476.0
mean       96.0       0.0   334683.0        2018.0          6099.0
std         3.0       1.0   669962.0           4.0         11359.0
min        85.0       0.0      100.0        2010.0            10.0
25%        95.0       0.0     2067.0        2014.0           281.0
50%        97.0       0.0    15639.0        2018.0           741.0
75%        98.0       0.0   360332.0        2021.0          6017.0
max       100.0       5.0  4999956.0        2024.0         49994.0

In [12]:
df_limpio = df.dropna() # Elimina valores nulos.

In [13]:
df_limpio.to_csv('limpio.csv')